# flake8: noqa
"""empty message

Revision ID: 18a48e68dba4
Revises:
Create Date: 2023-01-07 22:57:19.118833

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "18a48e68dba4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("password", sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("password")

    # ### end Alembic commands ###
