# flake8: noqa
"""add user confirmed column

Revision ID: 4b70efe62dfd
Revises: f11d875303f3
Create Date: 2023-01-13 17:16:31.538442

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4b70efe62dfd"
down_revision = "f11d875303f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("confirmed", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("confirmed")

    # ### end Alembic commands ###
