"""second migration

Revision ID: 68341a3bcda8
Revises: 18a48e68dba4
Create Date: 2023-01-09 17:25:14.418132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68341a3bcda8'
down_revision = '18a48e68dba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('pw_hash', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('pw_hash')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
